/*

UNIVERSIDAD NACIONAL DE COSTA RICA

PROGRAMACION I
PRIMER PROYECTO DE PROGRAMACION

ESTUDIANTES:
		IAN MORA RODRIGUEZ
		GIANCARLO ALVARADO SANCHEZ
PROFESORA:
		MARJORIE CHAVARRIA NERIO

AGOSTO - SEPTIEMBRE 2018

*/

#include "Control.h"
int main() {
	Control *control = new Control;
	control->opciones();
	return 0;
};